sudo: required
services:
  - docker

before_install:
  - docker build -t raghu1/docker-react -f Dockerfile.dev .
script: 
  - docker run -e CI=true raghu1/docker-react npm run test -- --coverage
language: generic
deploy: 
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "docker"
  env: "docker-env"
  bucket_name: "elasticbeanstalk-ap-south-1-665716692154"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"



# Docker-env.eba-mas8mmwr.ap-south-1.elasticbeanstalk.com