sudo: required
services:
  - docker

before_install:
  - docker build -t raghu1/docker-react -f Dockerfile.dev .
script: 
  - docker run -e CI=true raghu1/docker-react npm run test -- --coverage
language: generic  



